"""
Trading Bot - Database Models
SQLAlchemy models for persisting trading data.
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, Float, String, DateTime, Boolean, Enum, Text,
    create_engine
)
from sqlalchemy.orm import declarative_base, sessionmaker

Base = declarative_base()


class OHLCV(Base):
    """Candlestick data."""
    __tablename__ = "ohlcv"

    id = Column(Integer, primary_key=True, autoincrement=True)
    pair = Column(String(20), nullable=False, index=True)
    timeframe = Column(String(5), nullable=False)
    timestamp = Column(DateTime, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)

    def __repr__(self):
        return f"<OHLCV {self.pair} {self.timeframe} {self.timestamp} C:{self.close}>"


class Trade(Base):
    """Executed trades."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    pair = Column(String(20), nullable=False, index=True)
    side = Column(String(4), nullable=False)  # buy / sell
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float, nullable=True)
    amount = Column(Float, nullable=False)
    entry_time = Column(DateTime, nullable=False)
    exit_time = Column(DateTime, nullable=True)
    pnl = Column(Float, nullable=True)
    pnl_pct = Column(Float, nullable=True)
    status = Column(String(10), default="open")  # open / closed
    strategy = Column(String(50), nullable=True)
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)
    notes = Column(Text, nullable=True)

    def __repr__(self):
        return f"<Trade {self.side} {self.pair} @ {self.entry_price} | PnL: {self.pnl}>"


class Signal(Base):
    """Trading signals generated by strategies."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    pair = Column(String(20), nullable=False)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    strategy = Column(String(50), nullable=False)
    action = Column(String(10), nullable=False)  # buy / sell / hold
    strength = Column(Float, nullable=False)  # 0.0 to 1.0
    price_at_signal = Column(Float, nullable=False)
    ai_confidence = Column(Float, nullable=True)
    indicators = Column(Text, nullable=True)  # JSON string of indicator values
    executed = Column(Boolean, default=False)

    def __repr__(self):
        return f"<Signal {self.action} {self.pair} strength:{self.strength}>"


class BalanceHistory(Base):
    """Portfolio balance over time."""
    __tablename__ = "balance_history"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)
    total_balance = Column(Float, nullable=False)
    available_balance = Column(Float, nullable=False)
    in_positions = Column(Float, nullable=False)
    unrealized_pnl = Column(Float, default=0.0)
    daily_pnl = Column(Float, default=0.0)

    def __repr__(self):
        return f"<Balance {self.timestamp} total:{self.total_balance}>"
class PriceTick(Base):
    """Real-time price ticks."""
    __tablename__ = "price_ticks"

    id = Column(Integer, primary_key=True, autoincrement=True)
    pair = Column(String(20), nullable=False, index=True)
    price = Column(Float, nullable=False)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)

    def __repr__(self):
        return f"<Tick {self.pair} @ {self.price} | {self.timestamp}>"
